name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Lint Code Base
          uses: docker://github/super-linter:v2.2.0
          env:
            VALIDATE_ALL_CODEBASE: true

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build support Docker images
        run: |
          cd ./src/main/docker/orientdb && ./build.sh && cd -
          cd ./src/main/docker/postgresql-dvdrental && ./build.sh && cd -

      - name: Build with Maven
        run: mvn verify --file pom.xml
