name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Build support Docker images
        run: |
          cd ./src/main/docker/orientdb && ./build.sh && cd -
          cd ./src/main/docker/postgresql-dvdrental && ./build.sh && cd -

      - name: Build with Maven
        run: mvn verify --quiet --file pom.xml
